- static/css/poison.css
Hello!
This change removes vertical scrollbars on code blocks when they are not needed
> Hide vertical scrollbar on code blocks if content does not overflow

- README.md
- layouts/_default/list.html
For some reason, I had to format the dates differently on the list pages than on the single pages.  Not sure if I am just lacking knowledge or if this is some kind of Hugo bug, but either way I was able to fix it by formatting my dates with:
`.Date | time.Format ":date_long"`
instead of:
`.Date.Format "January 1, 2006"`
> Fixed date issue on list pages.

- static/css/hyde.css
This allows overflow content in the sidebar to still be viewable.
> Added a vertical scroll auto to sidebar

- static/js/katex.js
I added a line of JavaScript that fixes the issue. It replaces all instances of `\\$` with `<span>$</span>`. So going forward,  KaTeX can be escaped by putting a double backslash in front of dollar signs (like `\\$`) to represent a normal dollar sign.
> Issue 21 katex causing display issues

- README.md
Section pages (other than projects.md and about.md which have custom layouts) must be named `_index.html` in order to declare a branch bundle and therefore a SiteSection. The default layout for these pages is `list.html` and needs to be forced to `single.html` in order to display as a single page.
I know that this is not technically an issue, but as a new user I found it confusing and wondered for a while why I couldn't seem to add single pages in the menu other than 'about' and 'projects'
> Add note about single section pages to the README

- README.md
- layouts/partials/head/css.html
The default code colors are awesome! But it would be great if the user could theme it more to their tastes. :smile: 
This turns the code colors into variables so that the user can set them in config.toml
> Varaible out the code colors

- layouts/_default/baseof.html
- layouts/_default/single.html
- layouts/partials/table_of_contents.html
- static/css/hyde.css
- static/css/poison.css
- static/css/poole.css
These two commits switch the normal layout initially to flexbox and then the reverse layout.  It removes quite a bit of CSS, especially for the reverse layout and improves the layout of the TOC, menu and content.
Addresses: https://github.com/lukeorth/poison/issues/52
Allows future easier addressing of: https://github.com/lukeorth/poison/issues/51
**Normal Layout**
**Reverse Layout**
**Narrow Width**
As always, happy to take feedback, especially if anyone spots any bugs.
> Switch to flexbox for layout rather than using positioning and margins

- README.md
- layouts/partials/sidebar/socials.html
I wanted to be able to link directly to an email contact in the sidebar and noticed that icon isn't provided
> Add a social icon for direct emails

- layouts/partials/head/scripts.html
- layouts/shortcodes/mermaid.html
- layouts/shortcodes/plantuml.html
I noticed that the mermaid/plantuml diagrams do not render.
The reason is that the head/scripts.html is rendered first before the shortcode templates.
That means the .Page.store.Get is still false so the javascript doesn't get included.
> Fix mermaid and plantuml shortcode rendering.

- layouts/partials/post/info.html
Allows the use of the default post layout for categories that aren't necessarily dated.
> post/info: do not display date if not provided

- static/css/poison.css
It seemed sensible that code that's also a link should also take on the link color :)
**Before**
**After**
> Change code link color to --link-color

- assets/js/toc.js
Fixes a JS error when toc.js is included on pages that have headers but don't have a TOC sidebar (in my case, this happens on the homepage, for example).
I went for the most obvious/trivial fix but I don't fully understand this code, it could be there's a better solution that I've missed.
> js/toc: don't break on pages with no TOC sidebar

- layouts/index.html
I noticed that if i had posts in other sections which were being picked up by the Paginator, it would show weird behavior on the index page of the site.
For example only showing a single post if I had made 9 other posts in another section that shouldn't show up on the main page.
This commit changes it such that it filters to the "posts" section first, then paginates.
> FIX: Paginator behavior with other sections

- layouts/partials/head/scripts.html
The [self-hosted version](https://github.com/plausible/analytics) of [Plausible](https://plausible.io) is a great alternative to Google Analytics.  Once you have Plausible set up, tracking your site traffic is as simple as adding something like this to the ```<head>``` of each page:
```<script defer data-domain="myblog.com" src="https://plausible.myblog.com/js/script.js"></script>```
where "myblog.com" is the domain for your blog, and "plausible.myblog.com" is the FQDN or hostname for your plausible installation.  My proposal is to update the scripts.html file in layouts/partials/head/ so that you can optionally add support for Plausible.
Your sitewide config.toml would have this configuration to add support for plausible:
```
[params]
plausible = true
plausible_domain = "myblog.com" …
```
> Adding support for Plausible integration

- layouts/partials/sidebar/menu.html
I intend to create headings on the sidebar menu based on taxonomy terms. For instance, if a post is tagged with 'Development', my goal is to display the most recent posts under this tag in the sidebar menu. This functionality should also extend to posts that are part of a series.
This ensure the following works in my hugo.toml:
`[params]
menu = [
{Name = "Development", URL = "/tags/Development/", HasChildren = true, Limit = 2},
]
`
> Changed menu.html to add headings based on taxonomy terms

- README.md
- layouts/index.html
By default, the content assembled for the base page ("/") is filtered to include only "posts" content because it iterates over the `range` where `.Site.RegularPages "Type" "posts"`. This means that if a user has several non-"posts" page bundles listed in their sidebar, this content will not appear on the front page. This is also a problem if a site is structured so that it doesn't include a "posts" page bundle; in this case, nothing will appear on the front at all.
My pull request adds a new config parameter, `front_page_content`, which takes a list of page bundle names that will be included in the front page range. This is accomplished with minimal changes to the layouts/index.html file, to make it iterate over the `range` where their type is in the `front_page_content` list instead; it …
> Add parameter to configure base page content.

- assets/css/poole.css
this fixes an issue with some images displaying with weird aspect ratios, in particular on mobile.
without:
with:
> this fixes an issue with some images displaying with weird aspect ratios

- README.md
- assets/css/poison.css
- layouts/_default/single.html
- layouts/about/about.html
- layouts/partials/post/listmonk_email_newsletters.html
Here are the configs required to add to the `config.toml`/`hugo.toml` file:
```
listmonk = true 
listmonk_host = "https://listmonk.your_domain.tld"
listmonk_subscription_list_uiid = "YOUR_NEWSLETTERS_LIST_UIID"
listmonk_subscription_form_text = "Subscribe to my newsletters"                # default: Subscribe to my newsletters
listmonk_subscription_success__message = "Thanks for subscribing"         # default: Thanks for subscribing
listmonk_subcription_error_message = "Something went wrong"                  # default: Sorry, something went wrong. Please, try again
```
Here is how it looks for the dark theme:
and for the light one:
It is also added to the `About` page:
- dark:
- light:
The way it looks when the error happens:
- dark:
- light:
On successful subscription:
- dark:
- light:
> Implemented a possibility to enable email newsletters subscription by using Listmonk

- README.md
- layouts/partials/sidebar/title.html
I'm frequently updating my brand image in my blog, and every time, I need to include a new photo in the folder and update things manually.
Include a new param in `hugo.toml` to point to a remote image and use it in the sidebar, so people won't constantly need to update it manually.
In my case, I'd like my blog always to have the same avatar as I have in GitHub, so I can add a link to my GitHub account picture and use it instead.
- Easy to update
- Easy to configure
- Less handwork
- Go to my blog [https://lucasgrocha.com/](https://lucasgrocha.com/)
- Inspect my brand image
- Check the `src` attribute of the `<img>` tag
I updated my GitHub avatar and the blog has synced successfully with the GitHub by showing the new avatar there.
> Feat: Add ability to use remote brand image

- layouts/partials/head/meta.html
> Removed the `| humanize | title` from the webpage title to keep the text in the desired registry rather than forcing the uppercase one

- assets/css/poison.css
- layouts/partials/post/info.html
Most of the websites have a reading time element, and it's [recommended](https://tempestamedia.com/2022/12/21/why-its-important-to-add-an-estimated-reading-time/). It also makes the blog look more professional
- Update the `info.html` to include the reading time element and re-organize the HTML to take advantage of Flexbox
- Add CSS classes in `poison.css`
- Go to my blog [https://lucasgrocha.com/](https://lucasgrocha.com/)
Credits:
- The code to calculate the reading time was shared in this [comment](https://discourse.gohugo.io/t/readingtime-define/13036/4)
> Feat: Add reading time

- layouts/partials/sidebar/socials.html
Correctly render the RSS URL.
Fixes #157 and resolves one use of `BaseURL` as per #160.
> Fix RSS link (fixes #160 and #157)

- layouts/partials/sidebar/socials.html
Previously the RSS `href` would evaluate to the following:
If `rss_section` is set to `foo`, the RSS `href` is `/foo/index.xml`.
If `rss_section` is unset, the RSS `href` is `//index.xml`.
This patch moves the `/` into the conditional so that the RSS `href` now evalates to the following:
If `rss_section` is set to `foo`, the RSS `href` is `/foo/index.xml`.
If `rss_section` is unset, the RSS `href` is `/index.xml`.
Relates to #163.
> sidebar: update rss href

- layouts/partials/head/meta.html
- layouts/partials/sidebar/copyright.html
Some fixes:
* `.Site.Author` is deprecated
* `.Params.Author` might not be set
* `2001-02-03T14:05:06Z0700` is not a valid date format
> Fix bad date formatting and use newer Site.Params.Author

- layouts/partials/post/info.html
closes #170 
As discussed in the issue, if `author` is in the article's metadata add it just before the date in the post's info  
Moreover, if `author` is a taxonomy for the website make it an hyperlink to `/author/<author name>` 
Currently no CSS is added, and while the result seems good enough in dark mode with the hyperlink (see #170)   
without the hyperlink it can be a bit "poor"
I'd like to give it its own style, like tags but I'm not very creative when it comes to GUI...
~~Also, when listing an author's post, I believe `layouts/_default/list.html` is used to list terms of a taxonomy if I trust [the doc](https://gohugo.io/templates/lists/#list-defaults). But it "titlized" the taxonomy's term (here my nickname) thus not respecting the case:
`Ctmbl` instead of `ctmbl`  
this is …
> Add author in posts info

- layouts/partials/head/meta.html
closes #166.
Thanks for an amazing theme! This PR introduces a simple nil check with `{{ with $image_path }}` in _meta.html_ before the call to `fileExists $image_path_local`.
This change fixes the build issues on Windows machines as described in #166 and #148, as the build will no longer reach a `fileExists` call with a `"\assets\%!s(<nil>)"` argument, which is not a supported file path on Windows due to the percent sign.
> Safeguard meta.html fileExists for error-free build on Windows 

- README.md
- layouts/shortcodes/details.html
This commit adds a shortcode for collapsable markdown items.
```
{{< details summary="A summary" >}}
Markdown content
{{< /details >}}
```
> feat: Add collapsable details shortcode
